# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_profile_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='point',
            field=models.IntegerField(default=100),
        ),
    ]
