# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('draw_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='give_out_coupon', to='restaurants.Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_coupon', to='my_user.Profile'),
        ),
    ]
