# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw_restaurant', '0002_auto_20180114_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
