# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0003_auto_20180114_1655'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeenRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('been', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_user.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='guests',
            field=models.ManyToManyField(through='restaurants.BeenRestaurant', to='my_user.Profile'),
        ),
    ]
